FROM node:14.15.4-alpine3.12
WORKDIR /app
COPY package*.json ./
RUN apk add --no-cache build-base gcc autoconf automake libtool zlib-dev libpng-dev nasm
RUN npm ci
COPY . .
EXPOSE 3000
CMD ["sh", "-c", "npm start"]